//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace SolutionFactory.VSTemplateSchema
{
    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    [XmlRoot(Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable = false)]
    public partial class VSTemplate
    {
        private VSTemplateTemplateContent templateContentField;
        private VSTemplateTemplateData templateDataField;

        private string typeField;

        private string versionField;
        private VSTemplateWizardData[] wizardDataField;
        private VSTemplateWizardExtension[] wizardExtensionField;

        /// <remarks/>
        public VSTemplateTemplateData TemplateData
        {
            get { return templateDataField; }
            set { templateDataField = value; }
        }

        /// <remarks/>
        public VSTemplateTemplateContent TemplateContent
        {
            get { return templateContentField; }
            set { templateContentField = value; }
        }

        /// <remarks/>
        [XmlElement("WizardExtension")]
        public VSTemplateWizardExtension[] WizardExtension
        {
            get { return wizardExtensionField; }
            set { wizardExtensionField = value; }
        }

        /// <remarks/>
        [XmlElement("WizardData")]
        public VSTemplateWizardData[] WizardData
        {
            get { return wizardDataField; }
            set { wizardDataField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Type
        {
            get { return typeField; }
            set { typeField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Version
        {
            get { return versionField; }
            set { versionField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateData
    {
        private object buildOnLoadField;
        private object createInPlaceField;
        private bool createNewFolderField;

        private bool createNewFolderFieldSpecified;

        private string defaultNameField;
        private NameDescriptionIcon descriptionField;

        private bool enableEditOfLocationFieldField;

        private bool enableEditOfLocationFieldFieldSpecified;
        private bool enableLocationBrowseButtonField;

        private bool enableLocationBrowseButtonFieldSpecified;

        private bool hiddenField;

        private bool hiddenFieldSpecified;
        private NameDescriptionIcon iconField;
        private VSTemplateTemplateDataLocationField locationFieldField;

        private bool locationFieldFieldSpecified;

        private string locationFieldMRUPrefixField;
        private NameDescriptionIcon nameField;

        private string numberOfParentCategoriesToRollUpField;
        private string projectSubTypeField;
        private string projectTypeField;
        private bool promptForSaveOnCreationField;

        private bool promptForSaveOnCreationFieldSpecified;
        private bool provideDefaultNameField;

        private bool provideDefaultNameFieldSpecified;
        private VSTemplateTemplateDataRequiredFrameworkVersion requiredFrameworkVersionField;

        private bool requiredFrameworkVersionFieldSpecified;

        private object showByDefaultField;
        private string sortOrderField;

        private bool supportsCodeSeparationField;

        private bool supportsCodeSeparationFieldSpecified;

        private bool supportsLanguageDropDownField;

        private bool supportsLanguageDropDownFieldSpecified;
        private bool supportsMasterPageField;

        private bool supportsMasterPageFieldSpecified;
        private string templateGroupIDField;
        private string templateIDField;

        /// <remarks/>
        public NameDescriptionIcon Name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        public NameDescriptionIcon Description
        {
            get { return descriptionField; }
            set { descriptionField = value; }
        }

        /// <remarks/>
        public NameDescriptionIcon Icon
        {
            get { return iconField; }
            set { iconField = value; }
        }

        /// <remarks/>
        public string ProjectType
        {
            get { return projectTypeField; }
            set { projectTypeField = value; }
        }

        /// <remarks/>
        public string ProjectSubType
        {
            get { return projectSubTypeField; }
            set { projectSubTypeField = value; }
        }

        /// <remarks/>
        public string TemplateID
        {
            get { return templateIDField; }
            set { templateIDField = value; }
        }

        /// <remarks/>
        public string TemplateGroupID
        {
            get { return templateGroupIDField; }
            set { templateGroupIDField = value; }
        }

        /// <remarks/>
        [XmlElement(DataType = "integer")]
        public string SortOrder
        {
            get { return sortOrderField; }
            set { sortOrderField = value; }
        }

        /// <remarks/>
        public bool CreateNewFolder
        {
            get { return createNewFolderField; }
            set { createNewFolderField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool CreateNewFolderSpecified
        {
            get { return createNewFolderFieldSpecified; }
            set { createNewFolderFieldSpecified = value; }
        }

        /// <remarks/>
        public string DefaultName
        {
            get { return defaultNameField; }
            set { defaultNameField = value; }
        }

        /// <remarks/>
        public bool ProvideDefaultName
        {
            get { return provideDefaultNameField; }
            set { provideDefaultNameField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool ProvideDefaultNameSpecified
        {
            get { return provideDefaultNameFieldSpecified; }
            set { provideDefaultNameFieldSpecified = value; }
        }

        /// <remarks/>
        public bool PromptForSaveOnCreation
        {
            get { return promptForSaveOnCreationField; }
            set { promptForSaveOnCreationField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool PromptForSaveOnCreationSpecified
        {
            get { return promptForSaveOnCreationFieldSpecified; }
            set { promptForSaveOnCreationFieldSpecified = value; }
        }

        /// <remarks/>
        public bool EnableLocationBrowseButton
        {
            get { return enableLocationBrowseButtonField; }
            set { enableLocationBrowseButtonField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool EnableLocationBrowseButtonSpecified
        {
            get { return enableLocationBrowseButtonFieldSpecified; }
            set { enableLocationBrowseButtonFieldSpecified = value; }
        }

        /// <remarks/>
        public bool EnableEditOfLocationField
        {
            get { return enableEditOfLocationFieldField; }
            set { enableEditOfLocationFieldField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool EnableEditOfLocationFieldSpecified
        {
            get { return enableEditOfLocationFieldFieldSpecified; }
            set { enableEditOfLocationFieldFieldSpecified = value; }
        }

        /// <remarks/>
        public bool Hidden
        {
            get { return hiddenField; }
            set { hiddenField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool HiddenSpecified
        {
            get { return hiddenFieldSpecified; }
            set { hiddenFieldSpecified = value; }
        }

        /// <remarks/>
        public string LocationFieldMRUPrefix
        {
            get { return locationFieldMRUPrefixField; }
            set { locationFieldMRUPrefixField = value; }
        }

        /// <remarks/>
        [XmlElement(DataType = "integer")]
        public string NumberOfParentCategoriesToRollUp
        {
            get { return numberOfParentCategoriesToRollUpField; }
            set { numberOfParentCategoriesToRollUpField = value; }
        }

        /// <remarks/>
        public object CreateInPlace
        {
            get { return createInPlaceField; }
            set { createInPlaceField = value; }
        }

        /// <remarks/>
        public object BuildOnLoad
        {
            get { return buildOnLoadField; }
            set { buildOnLoadField = value; }
        }

        /// <remarks/>
        public object ShowByDefault
        {
            get { return showByDefaultField; }
            set { showByDefaultField = value; }
        }

        /// <remarks/>
        public VSTemplateTemplateDataLocationField LocationField
        {
            get { return locationFieldField; }
            set { locationFieldField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool LocationFieldSpecified
        {
            get { return locationFieldFieldSpecified; }
            set { locationFieldFieldSpecified = value; }
        }

        /// <remarks/>
        public bool SupportsMasterPage
        {
            get { return supportsMasterPageField; }
            set { supportsMasterPageField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool SupportsMasterPageSpecified
        {
            get { return supportsMasterPageFieldSpecified; }
            set { supportsMasterPageFieldSpecified = value; }
        }

        /// <remarks/>
        public bool SupportsCodeSeparation
        {
            get { return supportsCodeSeparationField; }
            set { supportsCodeSeparationField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool SupportsCodeSeparationSpecified
        {
            get { return supportsCodeSeparationFieldSpecified; }
            set { supportsCodeSeparationFieldSpecified = value; }
        }

        /// <remarks/>
        public bool SupportsLanguageDropDown
        {
            get { return supportsLanguageDropDownField; }
            set { supportsLanguageDropDownField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool SupportsLanguageDropDownSpecified
        {
            get { return supportsLanguageDropDownFieldSpecified; }
            set { supportsLanguageDropDownFieldSpecified = value; }
        }

        /// <remarks/>
        public VSTemplateTemplateDataRequiredFrameworkVersion RequiredFrameworkVersion
        {
            get { return requiredFrameworkVersionField; }
            set { requiredFrameworkVersionField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool RequiredFrameworkVersionSpecified
        {
            get { return requiredFrameworkVersionFieldSpecified; }
            set { requiredFrameworkVersionFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class NameDescriptionIcon
    {
        private string idField;
        private string packageField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string Package
        {
            get { return packageField; }
            set { packageField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string ID
        {
            get { return idField; }
            set { idField = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return valueField; }
            set { valueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum VSTemplateTemplateDataLocationField
    {
        /// <remarks/>
        Enabled,

        /// <remarks/>
        Disabled,

        /// <remarks/>
        Hidden,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public enum VSTemplateTemplateDataRequiredFrameworkVersion
    {
        /// <remarks/>
        [XmlEnum("2.0")] Item20,

        /// <remarks/>
        [XmlEnum("3.0")] Item30,

        /// <remarks/>
        [XmlEnum("3.5")] Item35,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContent
    {
        private VSTemplateTemplateContentCustomParameter[] customParametersField;
        private object[] itemsField;

        /// <remarks/>
        [XmlElement("Project", typeof (VSTemplateTemplateContentProject))]
        [XmlElement("ProjectCollection", typeof (VSTemplateTemplateContentProjectCollection))]
        [XmlElement("ProjectItem", typeof (VSTemplateTemplateContentProjectItem))]
        [XmlElement("References", typeof (VSTemplateTemplateContentReferences))]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks/>
        [XmlArrayItem("CustomParameter", IsNullable = false)]
        public VSTemplateTemplateContentCustomParameter[] CustomParameters
        {
            get { return customParametersField; }
            set { customParametersField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentProject
    {
        private string fileField;
        private object[] itemsField;

        private bool replaceParametersField;

        private bool replaceParametersFieldSpecified;
        private string targetFileNameField;

        /// <remarks/>
        [XmlElement("Folder", typeof (Folder))]
        [XmlElement("ProjectItem", typeof (ProjectItem))]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string File
        {
            get { return fileField; }
            set { fileField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string TargetFileName
        {
            get { return targetFileNameField; }
            set { targetFileNameField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool ReplaceParameters
        {
            get { return replaceParametersField; }
            set { replaceParametersField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool ReplaceParametersSpecified
        {
            get { return replaceParametersFieldSpecified; }
            set { replaceParametersFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    [XmlRoot(Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable = false)]
    public partial class Folder
    {
        private object[] itemsField;

        private string nameField;

        private string targetFolderNameField;

        /// <remarks/>
        [XmlElement("Folder", typeof (Folder))]
        [XmlElement("ProjectItem", typeof (ProjectItem))]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string TargetFolderName
        {
            get { return targetFolderNameField; }
            set { targetFolderNameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    [XmlRoot(Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable = false)]
    public partial class ProjectItem
    {
        private bool openInEditorField;

        private bool openInEditorFieldSpecified;

        private bool openInHelpBrowserField;

        private bool openInHelpBrowserFieldSpecified;
        private bool openInWebBrowserField;

        private bool openInWebBrowserFieldSpecified;
        private int openOrderField;

        private bool openOrderFieldSpecified;
        private bool replaceParametersField;

        private bool replaceParametersFieldSpecified;
        private string targetFileNameField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string TargetFileName
        {
            get { return targetFileNameField; }
            set { targetFileNameField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool ReplaceParameters
        {
            get { return replaceParametersField; }
            set { replaceParametersField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool ReplaceParametersSpecified
        {
            get { return replaceParametersFieldSpecified; }
            set { replaceParametersFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool OpenInEditor
        {
            get { return openInEditorField; }
            set { openInEditorField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool OpenInEditorSpecified
        {
            get { return openInEditorFieldSpecified; }
            set { openInEditorFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int OpenOrder
        {
            get { return openOrderField; }
            set { openOrderField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool OpenOrderSpecified
        {
            get { return openOrderFieldSpecified; }
            set { openOrderFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool OpenInWebBrowser
        {
            get { return openInWebBrowserField; }
            set { openInWebBrowserField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool OpenInWebBrowserSpecified
        {
            get { return openInWebBrowserFieldSpecified; }
            set { openInWebBrowserFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool OpenInHelpBrowser
        {
            get { return openInHelpBrowserField; }
            set { openInHelpBrowserField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool OpenInHelpBrowserSpecified
        {
            get { return openInHelpBrowserFieldSpecified; }
            set { openInHelpBrowserFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return valueField; }
            set { valueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentProjectCollection
    {
        private object[] itemsField;

        /// <remarks/>
        [XmlElement("ProjectTemplateLink", typeof (ProjectTemplateLink))]
        [XmlElement("SolutionFolder", typeof (SolutionFolder))]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    [XmlRoot(Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable = false)]
    public partial class ProjectTemplateLink
    {
        private string projectNameField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string ProjectName
        {
            get { return projectNameField; }
            set { projectNameField = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return valueField; }
            set { valueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    [XmlRoot(Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005", IsNullable = false)]
    public partial class SolutionFolder
    {
        private object[] itemsField;

        private string nameField;

        /// <remarks/>
        [XmlElement("ProjectTemplateLink", typeof (ProjectTemplateLink))]
        [XmlElement("SolutionFolder", typeof (SolutionFolder))]
        public object[] Items
        {
            get { return itemsField; }
            set { itemsField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentProjectItem
    {
        private bool replaceParametersField;

        private bool replaceParametersFieldSpecified;
        private string subTypeField;

        private string targetFileNameField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string SubType
        {
            get { return subTypeField; }
            set { subTypeField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool ReplaceParameters
        {
            get { return replaceParametersField; }
            set { replaceParametersField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool ReplaceParametersSpecified
        {
            get { return replaceParametersFieldSpecified; }
            set { replaceParametersFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string TargetFileName
        {
            get { return targetFileNameField; }
            set { targetFileNameField = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return valueField; }
            set { valueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentReferences
    {
        private VSTemplateTemplateContentReferencesReference referenceField;

        /// <remarks/>
        public VSTemplateTemplateContentReferencesReference Reference
        {
            get { return referenceField; }
            set { referenceField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentReferencesReference
    {
        private string assemblyField;

        /// <remarks/>
        public string Assembly
        {
            get { return assemblyField; }
            set { assemblyField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateTemplateContentCustomParameter
    {
        private string nameField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Value
        {
            get { return valueField; }
            set { valueField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateWizardExtension
    {
        private object[] assemblyField;

        private object[] fullClassNameField;

        /// <remarks/>
        [XmlElement("Assembly")]
        public object[] Assembly
        {
            get { return assemblyField; }
            set { assemblyField = value; }
        }

        /// <remarks/>
        [XmlElement("FullClassName")]
        public object[] FullClassName
        {
            get { return fullClassNameField; }
            set { fullClassNameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/vstemplate/2005")]
    public partial class VSTemplateWizardData
    {
        private XmlElement[] anyField;

        private string nameField;

        /// <remarks/>
        [XmlAnyElement()]
        public XmlElement[] Any
        {
            get { return anyField; }
            set { anyField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get { return nameField; }
            set { nameField = value; }
        }
    }
}

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 